---
title: "exploration"
output: html_document
---


```{r}
focal_sites <- c("BARC", "POSE")
# Will download everything the first time, and then only download updated files:
#Water quality
neonstore::neon_download("DP1.20288.001", site =  focal_sites, type = "basic")
#Precipiation: NOT WORKING!
#neonstore::neon_download("DP1.00006.001", site =  focal_sites, type = "basic")
# Wind Speed
neonstore::neon_download("DP1.20059.001", site =  focal_sites, type = "basic")
# Barometric Pressure
neonstore::neon_download("DP1.20004.001", site =  focal_sites, type = "basic")
# Air Temperature
Sys.sleep(100)
neonstore::neon_download("DP1.20046.001", site =  focal_sites, type = "basic")
# PAR at water surface
neonstore::neon_download("DP1.20042.001", site =  focal_sites, type = "basic")
Sys.sleep(100)
# PAR below water surface
neonstore::neon_download("DP1.20261.001", site =  focal_sites, type = "basic")
# Elevation of surface water
neonstore::neon_download("DP1.20016.001", site =  focal_sites, type = "basic")
Sys.sleep(100)
# Groundwater temperature
neonstore::neon_download("DP1.20217.001", site =  focal_sites, type = "basic")
# Nitrate in surface water
neonstore::neon_download("DP1.20033.001", site =  focal_sites, type = "basic")

```

```{r}
# will import downloaded files into local SQL DB:
neonstore::neon_store(product = "DP1.20288.001", type = "basic", n=1000) #Water Quality
#neonstore::neon_store(product = "DP1.00006.001", type = "basic") # Precip
neonstore::neon_store(product = "DP1.20059.001", type = "basic") # Wind Speed
neonstore::neon_store(product = "DP1.20004.001", type = "basic") # pressure
neonstore::neon_store(product = "DP1.20046.001", type = "basic") # temperature
```

```{r}
neonstore::neon_store(product = "DP1.20042.001", type = "basic") # PAR surface
neonstore::neon_store(product = "DP1.20261.001", type = "basic") # PAR below
neonstore::neon_store(product = "DP1.20016.001", type = "basic") # Elevation of surface water
neonstore::neon_store(product = "DP1.20217.001", type = "basic") # Groundwater temperature
neonstore::neon_store(product = "DP1.20033.001", type = "basic") # Nitrate
```
